spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true #在日志以及控制台输出sql语句
#日志
logging:
  level:
    root: warn
    com.fsj: info
  file:
    path: log/blog-pro.log
server:
  port: 8080
