spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #在日志以及控制台输出sql语句
#日志
logging:
  level:
    root: info
    com.fsj: debug
  file:
    path: log/blog-dev.log

